### PR TITLE
Fixed jumpy movement and other changes.

### PR DESCRIPTION
**Pull request by NathanSweet**
I fixed jumpy movement and made a few other changes. Each change is in a separate commit, feel free to cherry pick. The jumpy movement is most important. Inverted mouse and movement direction are good imprvements, IMO. The rest is more subjective.

Thanks for the plugin! SU is a PITA to use otherwise.

### CODE REVIEW

**Comment by LinearGraphs** [comment]
Greetings, I Have no idea how to apply your code changes to the existing RBZ extension. I know nothing about code or Github. I downloaded your fork file master, now what?
bandicam 2022-02-23 13-28-58-278

**Comment by NathanSweet** [comment]
Get the ZIP:
https://github.com/AlanChatham/FPSNav-for-SketchUp/archive/refs/heads/master.zip
Unzip it into your SketchUp user folder, for example:
C:\Users\<username>\AppData\Roaming\SketchUp\SketchUp 2020\SketchUp\Plugins
So in that folder you have "Chatham_FPSNav.rb" and a subfolder "FPSNav".
Restart SketchUp.

This project should have a README.md.

**Comment by LinearGraphs** [comment]
Thank you for the reply, So, It seems like you're saying I need to move the Chatham_FPSNav.rb into the plugins folder, then move the "thumbs" into the fps nav folder, like this, (Starting from the extraction):
block

 Then I need to put the fps nav folder into the plugins folder, like this:
block

**Comment by LinearGraphs** [comment]
Alright, I got it working, but why is movement not locked vertically anymore?

**Pull request merged**
